name:                sbv-newtypes
version:             0.1.0.0
github:              "lachrimae/sbv-newtypes"
author:              "Curran McConnell"
maintainer:          "curran@atidot.com"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/githubuser/sbv-newtypes#readme>

dependencies:
    - base >= 4.7 && < 5

library:
  source-dirs: src

executables:
  sbv-newtypes-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - sbv-newtypes
    - sbv == 8.6

tests:
  sbv-newtypes-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - sbv-newtypes
